openapi: 3.2.0
info:
  title: gridX Scan Configuration API
  description: The gridX standard API makes it possible to build customised energy applications.
  version: 2.0.0
  license:
    name: All rights reserved.
    url: https://www.gridx.ai/
  contact:
    name: gridX
    url: https://www.gridx.ai/module/api
    email: developer-community@gridx.de
  x-api-id: ba9d6a25-ae1a-4ac8-af7a-70b76db17021
  x-audience: public-external
servers:
- url: https://api.gridx.de
  description: Production
tags:
- name: Scan Configuration
  x-displayName: Scan Configuration
paths:
  /accounts/{accountID}/scanconfiguration:
    get:
      operationId: getScanConfiguration
      summary: Retrieve Scan Configuration
      tags:
      - Scan Configuration
      parameters:
      - name: accountID
        description: 'Unique identifier used to access an account.

          '
        in: path
        required: true
        schema:
          type: string
          format: uuid
        example: 17874c1b-d073-4b06-bf01-a1497fbe1142
      responses:
        '200':
          description: Scan configuration returned.
          content:
            application/vnd.gridx.v2+json:
              schema:
                title: ScanConfiguration
                description: ScanConfiguration determines the behavior of a scan.
                type: object
                properties:
                  accountID:
                    type: string
                    format: uuid
                    example: 6dd0a658-5828-4d30-bc65-a03c6d6e425f
                    description: The account ID the configuration belongs to.
                    readOnly: true
                  configuration:
                    description: The names of the scanners in this configuration.
                    type: array
                    items:
                      type: string
                  createdAt:
                    type: string
                    format: date-time
                    readOnly: true
                    description: Date when the configuration was created.
                  updatedAt:
                    type: string
                    format: date-time
                    readOnly: true
                    description: Date when the configuration was updated the last time.
                x-readme-ref-name: ScanConfiguration
        '404':
          description: Scan configuration not found.
          content:
            application/vnd.gridx.v2+json:
              schema:
                readOnly: true
                allOf:
                - title: General Exception
                  description: Represents a general error structure returned by our REST API.
                  type: object
                  properties:
                    message:
                      type: string
                      description: Message represents the message reported to the user.
                    details:
                      type: array
                      description: 'Details represents detail information for the user to fix this

                        problem

                        '
                      items:
                        type: string
                  required:
                  - message
                  x-readme-ref-name: GeneralException
                - title: ClientError - Not Found
                  description: Not Found indicates that the entity was not found.
                  example:
                    message: Not Found
                x-readme-ref-name: NotFoundException
        '422':
          description: Validation failed.
          content:
            application/vnd.gridx.v2+json:
              schema:
                readOnly: true
                allOf:
                - title: General Exception
                  description: Represents a general error structure returned by our REST API.
                  type: object
                  properties:
                    message:
                      type: string
                      description: Message represents the message reported to the user.
                    details:
                      type: array
                      description: 'Details represents detail information for the user to fix this

                        problem

                        '
                      items:
                        type: string
                  required:
                  - message
                  x-readme-ref-name: GeneralException
                - title: ClientError - Validation
                  description: 'Validation indicates that the request body contains fields which

                    does not pass the validation.

                    '
                  type: object
                  required:
                  - message
                  - details
                  example:
                    message: Validation failed
                    details:
                    - email is not valid
                x-readme-ref-name: InvalidException
        '500':
          description: There has been an internal error on our side. We're looking into it.
          content:
            application/vnd.gridx.v2+json:
              schema:
                readOnly: true
                allOf:
                - title: General Exception
                  description: Represents a general error structure returned by our REST API.
                  type: object
                  properties:
                    message:
                      type: string
                      description: Message represents the message reported to the user.
                    details:
                      type: array
                      description: 'Details represents detail information for the user to fix this

                        problem

                        '
                      items:
                        type: string
                  required:
                  - message
                  x-readme-ref-name: GeneralException
                - title: ServerSideError - Internal Server Error
                  description: Internal Server Error
                  example:
                    message: Internal Server Error
                x-readme-ref-name: InternalException
      security:
      - HeaderAuth:
        - ScanConfigurationRead
      x-code-samples:
      - lang: python
        label: Python
        source: 'import requests


          url = "https://api.gridx.de/accounts/accountID/scanconfiguration"


          headers = {"accept": "application/vnd.gridx.v2+json"}


          response = requests.get(url, headers=headers)


          print(response.text)'
      - lang: shell
        label: Shell
        source: "curl --request GET \\\n     --url https://api.gridx.de/accounts/accountID/scanconfiguration \\\n     --header 'accept: application/vnd.gridx.v2+json'"
      - lang: go
        label: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl := \"https://api.gridx.de/accounts/accountID/scanconfiguration\"\n\n\treq, _ := http.NewRequest(\"GET\", url, nil)\n\n\treq.Header.Add(\"accept\", \"application/vnd.gridx.v2+json\")\n\n\tres, _ := http.DefaultClient.Do(req)\n\n\tdefer res.Body.Close()\n\tbody, _ := io.ReadAll(res.Body)\n\n\tfmt.Println(string(body))\n\n}"
      - lang: javascript
        label: Javascript
        source: "const options = {method: 'GET', headers: {accept: 'application/vnd.gridx.v2+json'}};\n\nfetch('https://api.gridx.de/accounts/accountID/scanconfiguration', options)\n  .then(res => res.json())\n  .then(res => console.log(res))\n  .catch(err => console.error(err));"
      - lang: java
        label: Java
        source: "OkHttpClient client = new OkHttpClient();\n\nRequest request = new Request.Builder()\n  .url(\"https://api.gridx.de/accounts/accountID/scanconfiguration\")\n  .get()\n  .addHeader(\"accept\", \"application/vnd.gridx.v2+json\")\n  .build();\n\nResponse response = client.newCall(request).execute();"
      - lang: java
        label: Kotlin
        source: "val client = OkHttpClient()\n\nval request = Request.Builder()\n  .url(\"https://api.gridx.de/accounts/accountID/scanconfiguration\")\n  .get()\n  .addHeader(\"accept\", \"application/vnd.gridx.v2+json\")\n  .build()\n\nval response = client.newCall(request).execute()"
      - lang: javascript
        label: Swift
        source: 'import Foundation


          let url = URL(string: "https://api.gridx.de/accounts/accountID/scanconfiguration")!

          var request = URLRequest(url: url)

          request.httpMethod = "GET"

          request.timeoutInterval = 10

          request.allHTTPHeaderFields = ["accept": "application/vnd.gridx.v2+json"]


          let (data, _) = try await URLSession.shared.data(for: request)

          print(String(decoding: data, as: UTF8.self))'
      - lang: csharp
        label: C#
        source: 'using RestSharp;



          var options = new RestClientOptions("https://api.gridx.de/accounts/accountID/scanconfiguration");

          var client = new RestClient(options);

          var request = new RestRequest("");

          request.AddHeader("accept", "application/vnd.gridx.v2+json");

          var response = await client.GetAsync(request);


          Console.WriteLine("{0}", response.Content);

          '
    post:
      operationId: createScanConfiguration
      summary: Create a Scan Configuration
      tags:
      - Scan Configuration
      parameters:
      - name: accountID
        description: 'Unique identifier used to access an account.

          '
        in: path
        required: true
        schema:
          type: string
          format: uuid
        example: 17874c1b-d073-4b06-bf01-a1497fbe1142
      requestBody:
        description: Creates a scan configuration.
        required: true
        content:
          application/json:
            schema:
              allOf:
              - title: ScanConfiguration
                description: ScanConfiguration determines the behavior of a scan.
                type: object
                properties:
                  configuration:
                    description: The names of the scanners in this configuration.
                    type: array
                    items:
                      type: string
                x-readme-ref-name: ScanConfigurationSet
              - additionalProperties: false
              x-readme-ref-name: ScanConfigurationSetStrict
      responses:
        '201':
          description: Scan configuration created.
          content:
            application/vnd.gridx.v2+json:
              schema:
                title: ScanConfiguration
                description: ScanConfiguration determines the behavior of a scan.
                type: object
                properties:
                  accountID:
                    type: string
                    format: uuid
                    example: 6dd0a658-5828-4d30-bc65-a03c6d6e425f
                    description: The account ID the configuration belongs to.
                    readOnly: true
                  configuration:
                    description: The names of the scanners in this configuration.
                    type: array
                    items:
                      type: string
                  createdAt:
                    type: string
                    format: date-time
                    readOnly: true
                    description: Date when the configuration was created.
                  updatedAt:
                    type: string
                    format: date-time
                    readOnly: true
                    description: Date when the configuration was updated the last time.
                x-readme-ref-name: ScanConfiguration
        '422':
          description: Validation failed.
          content:
            application/vnd.gridx.v2+json:
              schema:
                readOnly: true
                allOf:
                - title: General Exception
                  description: Represents a general error structure returned by our REST API.
                  type: object
                  properties:
                    message:
                      type: string
                      description: Message represents the message reported to the user.
                    details:
                      type: array
                      description: 'Details represents detail information for the user to fix this

                        problem

                        '
                      items:
                        type: string
                  required:
                  - message
                  x-readme-ref-name: GeneralException
                - title: ClientError - Validation
                  description: 'Validation indicates that the request body contains fields which

                    does not pass the validation.

                    '
                  type: object
                  required:
                  - message
                  - details
                  example:
                    message: Validation failed
                    details:
                    - email is not valid
                x-readme-ref-name: InvalidException
        '500':
          description: There has been an internal error on our side. We're looking into it.
          content:
            application/vnd.gridx.v2+json:
              schema:
                readOnly: true
                allOf:
                - title: General Exception
                  description: Represents a general error structure returned by our REST API.
                  type: object
                  properties:
                    message:
                      type: string
                      description: Message represents the message reported to the user.
                    details:
                      type: array
                      description: 'Details represents detail information for the user to fix this

                        problem

                        '
                      items:
                        type: string
                  required:
                  - message
                  x-readme-ref-name: GeneralException
                - title: ServerSideError - Internal Server Error
                  description: Internal Server Error
                  example:
                    message: Internal Server Error
                x-readme-ref-name: InternalException
      security:
      - HeaderAuth:
        - ScanConfigurationWrite
      x-code-samples:
      - lang: python
        label: Python
        source: "import requests\n\nurl = \"https://api.gridx.de/accounts/accountID/scanconfiguration\"\n\nheaders = {\n    \"accept\": \"application/vnd.gridx.v2+json\",\n    \"content-type\": \"application/json\"\n}\n\nresponse = requests.post(url, headers=headers)\n\nprint(response.text)"
      - lang: shell
        label: Shell
        source: "curl --request POST \\\n     --url https://api.gridx.de/accounts/accountID/scanconfiguration \\\n     --header 'accept: application/vnd.gridx.v2+json' \\\n     --header 'content-type: application/json'"
      - lang: go
        label: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl := \"https://api.gridx.de/accounts/accountID/scanconfiguration\"\n\n\treq, _ := http.NewRequest(\"POST\", url, nil)\n\n\treq.Header.Add(\"accept\", \"application/vnd.gridx.v2+json\")\n\treq.Header.Add(\"content-type\", \"application/json\")\n\n\tres, _ := http.DefaultClient.Do(req)\n\n\tdefer res.Body.Close()\n\tbody, _ := io.ReadAll(res.Body)\n\n\tfmt.Println(string(body))\n\n}"
      - lang: javascript
        label: Javascript
        source: "const options = {\n  method: 'POST',\n  headers: {accept: 'application/vnd.gridx.v2+json', 'content-type': 'application/json'}\n};\n\nfetch('https://api.gridx.de/accounts/accountID/scanconfiguration', options)\n  .then(res => res.json())\n  .then(res => console.log(res))\n  .catch(err => console.error(err));"
      - lang: java
        label: Java
        source: "OkHttpClient client = new OkHttpClient();\n\nRequest request = new Request.Builder()\n  .url(\"https://api.gridx.de/accounts/accountID/scanconfiguration\")\n  .post(null)\n  .addHeader(\"accept\", \"application/vnd.gridx.v2+json\")\n  .addHeader(\"content-type\", \"application/json\")\n  .build();\n\nResponse response = client.newCall(request).execute();"
      - lang: java
        label: Kotlin
        source: "val client = OkHttpClient()\n\nval request = Request.Builder()\n  .url(\"https://api.gridx.de/accounts/accountID/scanconfiguration\")\n  .post(null)\n  .addHeader(\"accept\", \"application/vnd.gridx.v2+json\")\n  .addHeader(\"content-type\", \"application/json\")\n  .build()\n\nval response = client.newCall(request).execute()"
      - lang: javascript
        label: Swift
        source: "import Foundation\n\nlet url = URL(string: \"https://api.gridx.de/accounts/accountID/scanconfiguration\")!\nvar request = URLRequest(url: url)\nrequest.httpMethod = \"POST\"\nrequest.timeoutInterval = 10\nrequest.allHTTPHeaderFields = [\n  \"accept\": \"application/vnd.gridx.v2+json\",\n  \"content-type\": \"application/json\"\n]\n\nlet (data, _) = try await URLSession.shared.data(for: request)\nprint(String(decoding: data, as: UTF8.self))"
      - lang: csharp
        label: C#
        source: 'using RestSharp;



          var options = new RestClientOptions("https://api.gridx.de/accounts/accountID/scanconfiguration");

          var client = new RestClient(options);

          var request = new RestRequest("");

          request.AddHeader("accept", "application/vnd.gridx.v2+json");

          request.AddHeader("content-type", "application/json");

          var response = await client.PostAsync(request);


          Console.WriteLine("{0}", response.Content);

          '
    patch:
      operationId: updateScanConfiguration
      summary: Update a Scan Configuration
      tags:
      - Scan Configuration
      parameters:
      - name: accountID
        description: 'Unique identifier used to access an account.

          '
        in: path
        required: true
        schema:
          type: string
          format: uuid
        example: 17874c1b-d073-4b06-bf01-a1497fbe1142
      requestBody:
        description: Updates a scan configuration.
        required: true
        content:
          application/json:
            schema:
              allOf:
              - title: ScanConfiguration
                description: ScanConfiguration determines the behavior of a scan.
                type: object
                properties:
                  configuration:
                    description: The names of the scanners in this configuration.
                    type: array
                    items:
                      type: string
                x-readme-ref-name: ScanConfigurationSet
              - additionalProperties: false
              x-readme-ref-name: ScanConfigurationSetStrict
      responses:
        '200':
          description: Scan configuration updated.
          content:
            application/vnd.gridx.v2+json:
              schema:
                title: ScanConfiguration
                description: ScanConfiguration determines the behavior of a scan.
                type: object
                properties:
                  accountID:
                    type: string
                    format: uuid
                    example: 6dd0a658-5828-4d30-bc65-a03c6d6e425f
                    description: The account ID the configuration belongs to.
                    readOnly: true
                  configuration:
                    description: The names of the scanners in this configuration.
                    type: array
                    items:
                      type: string
                  createdAt:
                    type: string
                    format: date-time
                    readOnly: true
                    description: Date when the configuration was created.
                  updatedAt:
                    type: string
                    format: date-time
                    readOnly: true
                    description: Date when the configuration was updated the last time.
                x-readme-ref-name: ScanConfiguration
        '422':
          description: Validation failed.
          content:
            application/vnd.gridx.v2+json:
              schema:
                readOnly: true
                allOf:
                - title: General Exception
                  description: Represents a general error structure returned by our REST API.
                  type: object
                  properties:
                    message:
                      type: string
                      description: Message represents the message reported to the user.
                    details:
                      type: array
                      description: 'Details represents detail information for the user to fix this

                        problem

                        '
                      items:
                        type: string
                  required:
                  - message
                  x-readme-ref-name: GeneralException
                - title: ClientError - Validation
                  description: 'Validation indicates that the request body contains fields which

                    does not pass the validation.

                    '
                  type: object
                  required:
                  - message
                  - details
                  example:
                    message: Validation failed
                    details:
                    - email is not valid
                x-readme-ref-name: InvalidException
        '500':
          description: There has been an internal error on our side. We're looking into it.
          content:
            application/vnd.gridx.v2+json:
              schema:
                readOnly: true
                allOf:
                - title: General Exception
                  description: Represents a general error structure returned by our REST API.
                  type: object
                  properties:
                    message:
                      type: string
                      description: Message represents the message reported to the user.
                    details:
                      type: array
                      description: 'Details represents detail information for the user to fix this

                        problem

                        '
                      items:
                        type: string
                  required:
                  - message
                  x-readme-ref-name: GeneralException
                - title: ServerSideError - Internal Server Error
                  description: Internal Server Error
                  example:
                    message: Internal Server Error
                x-readme-ref-name: InternalException
      security:
      - HeaderAuth:
        - ScanConfigurationWrite
      x-code-samples:
      - lang: python
        label: Python
        source: "import requests\n\nurl = \"https://api.gridx.de/accounts/accountID/scanconfiguration\"\n\nheaders = {\n    \"accept\": \"application/vnd.gridx.v2+json\",\n    \"content-type\": \"application/json\"\n}\n\nresponse = requests.patch(url, headers=headers)\n\nprint(response.text)"
      - lang: shell
        label: Shell
        source: "curl --request PATCH \\\n     --url https://api.gridx.de/accounts/accountID/scanconfiguration \\\n     --header 'accept: application/vnd.gridx.v2+json' \\\n     --header 'content-type: application/json'"
      - lang: go
        label: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl := \"https://api.gridx.de/accounts/accountID/scanconfiguration\"\n\n\treq, _ := http.NewRequest(\"PATCH\", url, nil)\n\n\treq.Header.Add(\"accept\", \"application/vnd.gridx.v2+json\")\n\treq.Header.Add(\"content-type\", \"application/json\")\n\n\tres, _ := http.DefaultClient.Do(req)\n\n\tdefer res.Body.Close()\n\tbody, _ := io.ReadAll(res.Body)\n\n\tfmt.Println(string(body))\n\n}"
      - lang: javascript
        label: Javascript
        source: "const options = {\n  method: 'PATCH',\n  headers: {accept: 'application/vnd.gridx.v2+json', 'content-type': 'application/json'}\n};\n\nfetch('https://api.gridx.de/accounts/accountID/scanconfiguration', options)\n  .then(res => res.json())\n  .then(res => console.log(res))\n  .catch(err => console.error(err));"
      - lang: java
        label: Java
        source: "OkHttpClient client = new OkHttpClient();\n\nRequest request = new Request.Builder()\n  .url(\"https://api.gridx.de/accounts/accountID/scanconfiguration\")\n  .patch(null)\n  .addHeader(\"accept\", \"application/vnd.gridx.v2+json\")\n  .addHeader(\"content-type\", \"application/json\")\n  .build();\n\nResponse response = client.newCall(request).execute();"
      - lang: java
        label: Kotlin
        source: "val client = OkHttpClient()\n\nval request = Request.Builder()\n  .url(\"https://api.gridx.de/accounts/accountID/scanconfiguration\")\n  .patch(null)\n  .addHeader(\"accept\", \"application/vnd.gridx.v2+json\")\n  .addHeader(\"content-type\", \"application/json\")\n  .build()\n\nval response = client.newCall(request).execute()"
      - lang: javascript
        label: Swift
        source: "import Foundation\n\nlet url = URL(string: \"https://api.gridx.de/accounts/accountID/scanconfiguration\")!\nvar request = URLRequest(url: url)\nrequest.httpMethod = \"PATCH\"\nrequest.timeoutInterval = 10\nrequest.allHTTPHeaderFields = [\n  \"accept\": \"application/vnd.gridx.v2+json\",\n  \"content-type\": \"application/json\"\n]\n\nlet (data, _) = try await URLSession.shared.data(for: request)\nprint(String(decoding: data, as: UTF8.self))"
      - lang: csharp
        label: C#
        source: 'using RestSharp;



          var options = new RestClientOptions("https://api.gridx.de/accounts/accountID/scanconfiguration");

          var client = new RestClient(options);

          var request = new RestRequest("");

          request.AddHeader("accept", "application/vnd.gridx.v2+json");

          request.AddHeader("content-type", "application/json");

          var response = await client.PatchAsync(request);


          Console.WriteLine("{0}", response.Content);

          '
    delete:
      operationId: deleteScanConfiguration
      summary: Delete a Scan Configuration
      tags:
      - Scan Configuration
      parameters:
      - name: accountID
        description: 'Unique identifier used to access an account.

          '
        in: path
        required: true
        schema:
          type: string
          format: uuid
        example: 17874c1b-d073-4b06-bf01-a1497fbe1142
      responses:
        '204':
          description: Scan configuration deleted successfully.
        '422':
          description: Validation failed.
          content:
            application/vnd.gridx.v2+json:
              schema:
                readOnly: true
                allOf:
                - title: General Exception
                  description: Represents a general error structure returned by our REST API.
                  type: object
                  properties:
                    message:
                      type: string
                      description: Message represents the message reported to the user.
                    details:
                      type: array
                      description: 'Details represents detail information for the user to fix this

                        problem

                        '
                      items:
                        type: string
                  required:
                  - message
                  x-readme-ref-name: GeneralException
                - title: ClientError - Validation
                  description: 'Validation indicates that the request body contains fields which

                    does not pass the validation.

                    '
                  type: object
                  required:
                  - message
                  - details
                  example:
                    message: Validation failed
                    details:
                    - email is not valid
                x-readme-ref-name: InvalidException
        '500':
          description: There has been an internal error on our side. We're looking into it.
          content:
            application/vnd.gridx.v2+json:
              schema:
                readOnly: true
                allOf:
                - title: General Exception
                  description: Represents a general error structure returned by our REST API.
                  type: object
                  properties:
                    message:
                      type: string
                      description: Message represents the message reported to the user.
                    details:
                      type: array
                      description: 'Details represents detail information for the user to fix this

                        problem

                        '
                      items:
                        type: string
                  required:
                  - message
                  x-readme-ref-name: GeneralException
                - title: ServerSideError - Internal Server Error
                  description: Internal Server Error
                  example:
                    message: Internal Server Error
                x-readme-ref-name: InternalException
      security:
      - HeaderAuth:
        - ScanConfigurationWrite
      x-code-samples:
      - lang: python
        label: Python
        source: 'import requests


          url = "https://api.gridx.de/accounts/accountID/scanconfiguration"


          headers = {"accept": "application/vnd.gridx.v2+json"}


          response = requests.delete(url, headers=headers)


          print(response.text)'
      - lang: shell
        label: Shell
        source: "curl --request DELETE \\\n     --url https://api.gridx.de/accounts/accountID/scanconfiguration \\\n     --header 'accept: application/vnd.gridx.v2+json'"
      - lang: go
        label: Go
        source: "package main\n\nimport (\n\t\"fmt\"\n\t\"net/http\"\n\t\"io\"\n)\n\nfunc main() {\n\n\turl := \"https://api.gridx.de/accounts/accountID/scanconfiguration\"\n\n\treq, _ := http.NewRequest(\"DELETE\", url, nil)\n\n\treq.Header.Add(\"accept\", \"application/vnd.gridx.v2+json\")\n\n\tres, _ := http.DefaultClient.Do(req)\n\n\tdefer res.Body.Close()\n\tbody, _ := io.ReadAll(res.Body)\n\n\tfmt.Println(string(body))\n\n}"
      - lang: javascript
        label: Javascript
        source: "const options = {method: 'DELETE', headers: {accept: 'application/vnd.gridx.v2+json'}};\n\nfetch('https://api.gridx.de/accounts/accountID/scanconfiguration', options)\n  .then(res => res.json())\n  .then(res => console.log(res))\n  .catch(err => console.error(err));"
      - lang: java
        label: Java
        source: "OkHttpClient client = new OkHttpClient();\n\nRequest request = new Request.Builder()\n  .url(\"https://api.gridx.de/accounts/accountID/scanconfiguration\")\n  .delete(null)\n  .addHeader(\"accept\", \"application/vnd.gridx.v2+json\")\n  .build();\n\nResponse response = client.newCall(request).execute();"
      - lang: java
        label: Kotlin
        source: "val client = OkHttpClient()\n\nval request = Request.Builder()\n  .url(\"https://api.gridx.de/accounts/accountID/scanconfiguration\")\n  .delete(null)\n  .addHeader(\"accept\", \"application/vnd.gridx.v2+json\")\n  .build()\n\nval response = client.newCall(request).execute()"
      - lang: javascript
        label: Swift
        source: 'import Foundation


          let url = URL(string: "https://api.gridx.de/accounts/accountID/scanconfiguration")!

          var request = URLRequest(url: url)

          request.httpMethod = "DELETE"

          request.timeoutInterval = 10

          request.allHTTPHeaderFields = ["accept": "application/vnd.gridx.v2+json"]


          let (data, _) = try await URLSession.shared.data(for: request)

          print(String(decoding: data, as: UTF8.self))'
      - lang: csharp
        label: C#
        source: 'using RestSharp;



          var options = new RestClientOptions("https://api.gridx.de/accounts/accountID/scanconfiguration");

          var client = new RestClient(options);

          var request = new RestRequest("");

          request.AddHeader("accept", "application/vnd.gridx.v2+json");

          var response = await client.DeleteAsync(request);


          Console.WriteLine("{0}", response.Content);

          '
components:
  securitySchemes:
    HeaderAuth:
      type: apiKey
      name: Authorization
      in: header
      description: Enter either the JWT token with the prefix `Bearer ` or an API token with the prefix `Token `
